export default {
  CREATE_BUSINESS_INSTANCE:"CREATE_BUSINESS_INSTANCE",
  ADD_BUSINESS_INSTANCE:"ADD_BUSINESS_INSTANCE",
  SUCCESS_ADD_BUSINESS_INSTANCE:"SUCESS_ADD_BUSINESS_INSTANCE",
  ERROR_ADD_BUSINESS_INSTANCE:"ERROR_ADD_BUSINESS_INSTANCE",
  FETCH_BUSINESS_INSTANCES:"FETCH_BUSINESS_INSTANCES",
  SET_BUSINESS_INSTANCES:"SET_BUSINESS_INSTANCES",
  RESET_CREATE_BUSINESS_INSTANCE:"RESET_CREATE_BUSINESS_INSTANCE",
}