export default {
  FETCH_ALL_STRUCTURES:"FETCH_ALL_STRUCTURES",
  GET_STRUCTURE_CATEGORY:"GET_STRUCTURE_CATEGORY",
  ADD_MULTIPLE_VALUE:"ADD_MULTIPLE_VALUE",
  ADD_FIELD_CATEGORY:"ADD_FIELD_CATEGORY",
  REMOVE_FIELD_CATEGORY:"REMOVE_FIELD_CATEGORY",
  CREATE_STRUCTURE_EMPTY:"CREATE_STRUCTURE_EMPTY",
  GET_FORM_FIELDS:"GET_FORM_FIELDS",
}