export default {
  FETCH_ALL_STRUCTURES:"FETCH_ALL_STRUCTURES",
  GET_STRUCTURE_CATEGORY:"GET_STRUCTURE_CATEGORY",
  ADD_MULTIPLE_VALUE:"ADD_MULTIPLE_VALUE",
  ADD_FIELD_CATEGORY:"ADD_FIELD_CATEGORY",
  REMOVE_FIELD_CATEGORY:"REMOVE_FIELD_CATEGORY",
  CREATE_STRUCTURE_EMPTY:"CREATE_STRUCTURE_EMPTY",
  GET_FORM_FIELDS:"GET_FORM_FIELDS",
  CREATE_PRODUCT_FROM_STRUCTURE:"CREATE_PRODUCT_FROM_STRUCTURE",
  GET_PRODUCTS_FROM_STRUCTURE:"GET_PRODUCTS_FROM_STRUCTURE",
  DELETE_PRODUCT_FROM_STRUCTURE:"DELETE_PRODUCT_FROM_STRUCTURE",
  EDIT_PRODUCT_FROM_STRUCTURE:"EDIT_PRODUCT_FROM_STRUCTURE",
  GET_ALL_PRODUCTS_FROM_CATEGORY_DOWN:"GET_ALL_PRODUCTS_FROM_CATEGORY_DOWN",
  ADD_FIELD_CRITERIA:"ADD_FIELD_CRITERIA",
  REMOVE_FIELD_CRITERIA:"REMOVE_FIELD_CRITERIA",
  FETCH_FILTER_RESULTS:"FETCH_FILTER_RESULTS",
  DELETE_ALL_FILTERS:"DELETE_ALL_FILTERS"

}