export default {
  ALL_CATEGORIES:"ALL_PRODUCTS",
  FETCH_CATEGORIES:"FETCH_CATEGORIES",
  SET_CATEGORIES:"SET_CATEGORIES",
  SEARCH_CATEGORIES:"SEARCH_CATEGORIES",
  SET_SEARCH_CATEGORIES:"SET_SEARCH_CATEGORIES",
  ADD_PRODUCT:"ADD_PRODUCT",
  CREATE_PRODUCT:"CREATE_PRODUCT"

}