export default {
  ALL_CATEGORIES:"ALL_PRODUCTS",
  SET_CATEGORIES:"SET_CATEGORIES",
  SET_SEARCH_CATEGORIES:"SET_SEARCH_CATEGORIES",
  ADD_PRODUCT:"ADD_PRODUCT",
  GET_PRODUCT_CATEGORIES:"GET_PRODUCT_CATEGORIES",

  //sagas
  FETCH_CATEGORIES:"FETCH_CATEGORIES",
  SEARCH_CATEGORIES:"SEARCH_CATEGORIES",
  CREATE_PRODUCT:"CREATE_PRODUCT",

  //nuevas
  GET_CATEGORY:"GET_CATEGORY",

}