export default {
  GET_ALL_INVOICES:"GET_ALL_INVOICES",
  GET_INVOICES_FROM_CLIENT:"GET_INVOICES_FROM_CLIENT",
  ADD_INVOICE:"ADD_INVOICE",
  SEARCH_INVOICES:"SEARCH_INVOICES",
  SET_CURRENT_INVOICE:"SET_CURRENT_INVOICE",
  
}