export default {
  CREATE_INVOICE_DETAIL:"CREATE_INVOICE_DETAIL", 
  GET_INVOICE_DETAILS:"GET_INVOICE_DETAILS",
  SET_INVOICE_DETAIL:"SET_INVOICE_DETAIL",
  EDIT_INVOICE_DETAIL:"EDIT_INVOICE_DETAIL",
  DELETE_INVOICE_DETAIL:"DELETE_INVOICE_DETAIL",
}
  