const types={
  ADD_QUERY_FIELD:"ADD_QUERY_FIELD",
  REMOVE_QUERY_FIELD:"REMOVE_QUERY_FIELD",
  ADD_QUERY_GROUP:"ADD_QUERY_GROUP",
  REMOVE_QUERY_GROUP:"REMOVE_QUERY_GROUP",
  CREATE_REPORT:"CREATE_REPORT",
  SELECT_CATEGORY_REPORTS:"SELECT_CATEGORY_REPORTS",
  RUN_REPORT:"RUN_REPORT",
  GET_REPORT:"GET_REPORT",
  DISPLAY_REPORT:"DISPLAY_REPORT"
}
export default types