const businessTypes={
  CREATE_BUSINESS:"CREATE_BUSINESS",
  ADD_BUSINESS:"ADD_BUSINESS",
  SUCCESS_CREATE_BUSINESS:"SUCCESS_CREATE_BUSINESS",
  ERROR_CREATE_BUSINESS:"ERROR_CREATE_BUSINESS",
  RESET_CREATE_BUSINESS:"RESET_CREATE_BUSINESS",
  FETCH_BUSINESSES:"FETCH_BUSINESSES",
  SET_BUSINESSES:"SET_BUSINESSES",
  SEARCH_BUSINESS:"SEARCH_BUSINESS",
  SET_FILTER:"SET_FILTER",
  SET_SEARCH_LABEL:"SET_SEARCH_LABEL"

}

export default businessTypes;