const businessTypes={
  CREATE_BUSINESS:"CREATE_BUSINESS",
  ADD_BUSINESS:"ADD_BUSINESS",
  SUCCESS_CREATE_BUSINESS:"SUCCESS_CREATE_BUSINESS",
  ERROR_CREATE_BUSINESS:"ERROR_CREATE_BUSINESS",
  RESET_CREATE_BUSINESS:"RESET_CREATE_BUSINESS",
  FETCH_BUSINESSES:"FETCH_BUSINESSES",
  SET_BUSINESSES:"SET_BUSINESSES",

}

export default businessTypes;